# 3.数字、日期和时间

## 3.1对数值进行取整

In [1]:
# 简单操作
round(1.123, 2)

1.12

In [2]:
round(123.456, -2)

100.0

讨论：不能把取整和格式化混为一谈。也不要采用取整的方法修正精度问题。

In [3]:
a = 2.1
b = 4.2
a+b

6.300000000000001

In [4]:
round(a+b,2)

6.3

## 3.2执行精确的小数计算

In [5]:
a + b == 6.3

False

In [6]:
from decimal import Decimal
a = Decimal("2.1")
b = Decimal("4.3")
a + b

Decimal('6.4')

In [7]:
print(a + b)

6.4


In [8]:
a + b == Decimal("6.4") # 注意接收的是string

True

decimal用于控制计算过程的各个方面，包括数字位数和四舍五入. 需要建立一个本地的上下文环境然后修改其设定

In [9]:
from decimal import localcontext
a = Decimal("2.1")
b = Decimal("4.3")

In [10]:
print(a/b)

0.4883720930232558139534883721


In [11]:
with localcontext() as ctx:
    ctx.prec = 3
    print(a/b)

0.488


In [12]:
with localcontext() as ctx:
    ctx.prec = 50
    print(a/b)

0.48837209302325581395348837209302325581395348837209


**在一般科学领域，float的精度完全能满足需求，所以Decimal主要用在对误差要求严格的金融行业。**
**decimal实现了IBM的计算规范**

## 3.3对数值进行格式化输出

In [13]:
import math
pai = math.pi

In [14]:
pai

3.141592653589793

In [15]:
format(pai, "0.2f")

'3.14'

In [16]:
format(pai*10000, ">10.3f")

' 31415.927'

In [17]:
format(pai*100, "e")

'3.141593e+02'

In [18]:
# 制定宽度和精度一般格式“[<>^]width[,]?(.digits)”
"value = {:0,.2f}".format(1000*pai)

'value = 3,141.59'

## 3.4同二进制、八进制、和十六进制打交道

In [19]:
x = 1234
# 2 jinzhi
print(bin(x))

# 8 jinzhi
print(oct(x))

# 16jinzhi
print(hex(x))

0b10011010010
0o2322
0x4d2


In [20]:
# 如果不希望出现0b 0o 0x
format(x, "b")

'10011010010'

In [21]:
format(x, "o")

'2322'

In [22]:
format(x, "x")

'4d2'

In [23]:
# 如果要产生无符号的数值，需要加上最大值设置比特位的长度。比如要产生一个32位数：
x = -123
format(2**32 + x, "b")

'11111111111111111111111110000101'

## 3.5从字节串中解包和打包大整数

In [24]:
# 略

## 3.6复数运算

In [25]:
# 复数通常使用complex（real, imag）指定
a = complex(1 , 2)
a

(1+2j)

In [26]:
a.real

1.0

In [27]:
a.imag

2.0

In [28]:
# 所有复数运算基本等同实数运算
b = complex(2, 3)

In [29]:
a + b

(3+5j)

In [30]:
# function
import cmath
cmath.sin(a)

(3.165778513216168+1.959601041421606j)

In [31]:
cmath.exp(a)

(-1.1312043837568135+2.4717266720048188j)

# 3.7处理无穷大和NaN

我们需要对浮点数的无穷大和nan（not a number）操作

In [32]:
a = float("inf")

In [33]:
b = float("-inf")

In [34]:
a

inf

In [35]:
b

-inf

In [36]:
c = float("nan")
c

nan

In [37]:
# 检测是否出现这些值，可以使用math.isinf()和math.isnan()函数
math.isinf(a)

True

In [38]:
math.isnan(c)

True

讨论：

In [39]:
# 具体的浮点数详细信息，参考IEEE745规范。
# 无穷大的传播
a

inf

In [40]:
a + 45

inf

In [41]:
a * 10

inf

In [42]:
10 / a

0.0

In [43]:
a / a

nan

In [44]:
b

-inf

In [45]:
a + b

nan

In [46]:
d = float("nan")

In [47]:
c == d # 同样的nan并不想等

False

# 3.8分数的计算

In [48]:
from fractions import Fraction
a = Fraction(1 ,3)

In [49]:
a

Fraction(1, 3)

In [50]:
print(a)

1/3


In [51]:
b = Fraction(1 ,9)

In [52]:
a * b

Fraction(1, 27)

In [53]:
float(a*b)

0.037037037037037035

# 3.9处理大型数组的计算

对于大型的数据集 比如数组和网格grid

In [54]:
# 大型数组的密集运算，使用Mumpy库。 性能比一般列表高。 下面说明其与列表的几个不同之处
x = [i for i in range(5)]
y = [j for j in range(5, 10)]

In [55]:
x * 2

[0, 1, 2, 3, 4, 0, 1, 2, 3, 4]

In [56]:
x + 10

TypeError: can only concatenate list (not "int") to list

In [57]:
x + y

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [58]:
# numpy
import numpy as np
ax = np.array(x)
ay = np.array(y)

In [59]:
ax * 2

array([0, 2, 4, 6, 8])

In [60]:
ax + ay

array([ 5,  7,  9, 11, 13])

In [61]:
ax + 10

array([10, 11, 12, 13, 14])

In [62]:
np.sqrt(ax)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ])

In [63]:
np.sin(ay)

array([-0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

这种方式比使用列表迭代快上百倍

In [64]:
grid = np.zeros(shape=(1000,1000), dtype="float")

In [65]:
grid

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [66]:

grid = grid + 10
grid

array([[10., 10., 10., ..., 10., 10., 10.],
       [10., 10., 10., ..., 10., 10., 10.],
       [10., 10., 10., ..., 10., 10., 10.],
       ...,
       [10., 10., 10., ..., 10., 10., 10.],
       [10., 10., 10., ..., 10., 10., 10.],
       [10., 10., 10., ..., 10., 10., 10.]])

In [67]:
np.sin(grid)

array([[-0.54402111, -0.54402111, -0.54402111, ..., -0.54402111,
        -0.54402111, -0.54402111],
       [-0.54402111, -0.54402111, -0.54402111, ..., -0.54402111,
        -0.54402111, -0.54402111],
       [-0.54402111, -0.54402111, -0.54402111, ..., -0.54402111,
        -0.54402111, -0.54402111],
       ...,
       [-0.54402111, -0.54402111, -0.54402111, ..., -0.54402111,
        -0.54402111, -0.54402111],
       [-0.54402111, -0.54402111, -0.54402111, ..., -0.54402111,
        -0.54402111, -0.54402111],
       [-0.54402111, -0.54402111, -0.54402111, ..., -0.54402111,
        -0.54402111, -0.54402111]])

更多numpy使用见《利用python进行数据分析》

## 3.10矩阵和线性代数的运算

In [68]:
import numpy as np
m = np.matrix([[1,2,3],[1,2,5],[3,2,1]])

In [69]:
m

matrix([[1, 2, 3],
        [1, 2, 5],
        [3, 2, 1]])

In [70]:
m.T

matrix([[1, 1, 3],
        [2, 2, 2],
        [3, 5, 1]])

In [71]:
m.I

matrix([[-1.  ,  0.5 ,  0.5 ],
        [ 1.75, -1.  , -0.25],
        [-0.5 ,  0.5 , -0.  ]])

## 3.11随机选择

In [72]:
import random
values = [i for i in range(1,10)]

In [73]:
random.choice(values)

1

In [74]:
random.sample(values, 2)

[3, 6]

In [75]:
# 打乱顺序
random.shuffle(values)

In [76]:
values

[2, 3, 5, 1, 8, 6, 9, 4, 7]

In [77]:
# 随机整数
random.randint(0, 10)

0

In [78]:
# 0-1之间均匀分布的浮点数值
random.random()

0.8441265745039929

random是一个采用马塞特旋转法来计算的随机数。是一个确定性的算法，但可以通过random.seed()来改变初始种子。如果需要加密处理，应该使用ssl模块函数来代替。

## 3.12时间转换

In [79]:
# datetime

from datetime import timedelta
a = timedelta(days=3, hours=6)
b = timedelta(hours=3.5)

In [80]:
c = a+b

In [81]:
c

datetime.timedelta(3, 34200)

In [82]:
c.days

3

In [83]:
c.seconds

34200

In [84]:
c.total_seconds()

293400.0

In [85]:
# 如果需要特定的日期，可以创建datetime实例并使用标准的数学运算来操纵他们
from datetime import datetime
a = datetime(2012, 9, 23)

In [86]:
a

datetime.datetime(2012, 9, 23, 0, 0)

In [87]:
print(a + timedelta(days=1))

2012-09-24 00:00:00


In [88]:
b = datetime(2018,12,29)

In [89]:
c = b-a
c

datetime.timedelta(2288)

In [90]:
c.days

2288

In [91]:
now = datetime.today() #当地时间

In [92]:
now

datetime.datetime(2018, 12, 29, 16, 23, 16, 619235)

In [93]:
print(now)

2018-12-29 16:23:16.619235


## 3.15将字符串转换为日期

In [94]:
from datetime import datetime
text = "2018/12/29"

In [95]:
y = datetime.strptime(text, "%Y/%m/%d")

In [96]:
y

datetime.datetime(2018, 12, 29, 0, 0)

In [97]:
z = datetime.now()

In [98]:
z

datetime.datetime(2018, 12, 29, 16, 23, 16, 733811)

In [99]:
nice_z = datetime.strftime(z, "%Y %m %d %H:%M:%S")

In [100]:
nice_z

'2018 12 29 16:23:16'

In [101]:
datetime.strftime(z, "%y %B %d %A %H:%M:%S")

'18 December 29 Saturday 16:23:16'

## 3.16涉及时区的处理

In [102]:
from datetime import datetime
from pytz import timezone
d = datetime.now()
d

datetime.datetime(2018, 12, 29, 16, 23, 16, 826066)

In [103]:
central = timezone("US/Central")
local_d = central.localize(d)
print(local_d)

2018-12-29 16:23:16.826066-06:00


In [104]:
Tokyo = local_d.astimezone(timezone("Asia/Tokyo"))

In [105]:
Tokyo

datetime.datetime(2018, 12, 30, 7, 23, 16, 826066, tzinfo=<DstTzInfo 'Asia/Tokyo' JST+9:00:00 STD>)

In [106]:
# UTC时间
import pytz
utc = local_d.astimezone(pytz.utc)

In [107]:
utc

datetime.datetime(2018, 12, 29, 22, 23, 16, 826066, tzinfo=<UTC>)